services:
  api_service:
    container_name: api_service
    build:
      context: ../api_service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - ../api_service/:/app
    env_file:
      - ../api_service/.env
      - ../.env.db
      - ../.env.shared

  etl_service:
    container_name: etl_service
    build:
      context: ../etl_service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ../etl_service/:/app
    env_file:
      - ../etl_service/.env
      - ../.env.shared

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env.db

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file: 
      - ../.env.shared
    command: >
      sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
    restart: always
    volumes:
      - redis_data:/data

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ../.env.shared

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: